### PR TITLE
Add catch for location permissions exception (closes #23)

### LINKED ISSUE #23: requestLocationUpdates() throws if location services haven't been granted yet

### PR DESCRIPTION
**Pull request by wilsonpage**

### CODE REVIEW

**Comment by wilsonpage** [comment]
@arcturus r?

**Comment by arcturus** [comment]
Do you think that makes sense to ask for permissions if we 'catch' the exception? I'm thinking that will conflict with our mechanism to ask for permissions right?

Anyway, shiiiiip.ly

**Comment by wilsonpage** [comment]
I admit it's a lazy fix. We could put the checks in our app code before running any scanner related logic. This particular catch was for the background scanner that triggers `onPause` when the location permission prompt comes up on app start.

**Comment by arcturus** [comment]
Lets land it and open a follow up for proper fixing.

**Comment by wilsonpage** [comment]
I think it's still good to have this `catch` in the library as we should protect the library from crashing apps. Following Android M we can't be sure if/when the user has granted location permissions. But we should protect our background scanner from running before all required permission checks have been granted.

**Pull request merged**
